# Generated by Django 5.2.6 on 2025-11-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetOwnerDashboard', '0001_initial'),
        ('RegistrationPage', '0002_petsitterprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pets',
            field=models.ManyToManyField(related_name='bookings', to='RegistrationPage.pet'),
        ),
    ]
