# Generated by Django 5.2.6 on 2025-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsitterprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='sitter_profiles/'),
        ),
    ]
