# Generated by Django 5.2.6 on 2025-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationPage', '0002_petsitterprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsitterprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='petsitterprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
